name: Deploy to Render

on:
  push:
    branches:
      - main  # This can be changed to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run Migrations
      run: |
        python manage.py migrate --noinput

    - name: Collect Static Files 
      run: |
        python manage.py collectstatic --noinput
        
    - name: Deploy to Render
      run: |
        curl -X POST https://api.render.com/deploy/https://api.render.com/deploy/srv-cvm0sure5dus73adtg60?key=wRTxKYqk5FA
